# Generated by Django 4.1.1 on 2022-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_commentaire_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
