# Generated by Django 4.1.1 on 2022-10-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Référence'),
        ),
    ]
