# Generated by Django 4.1.1 on 2022-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_entreprise_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/logos/'),
        ),
    ]
